accounts/urls.py
from django.conf.urls import url


from .views import (
    login_view,
    register_view,
    logout_view
)


urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
]

bankingsystem/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from core.views import home, about


urlpatterns = [
    # admin
    url(r'^admin/', admin.site.urls),
    # Accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    # transactions
    url(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.conf.urls import url

from .views import deposit_view, withdrawal_view

urlpatterns = [
    # url(r'^$', home_view, name='home'),
    url(r'^deposit/$', deposit_view, name='deposit'),
    url(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
    RegexValidator,
)
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from transactions.models import DepositProduct
from .managers import UserManager


class User(AbstractUser):
    username = models.CharField(
        _('username'), max_length=30, unique=True, null=True, blank=True,
        help_text=_(
            'Required. 30 characters or fewer. Letters, digits and '
            '@/./+/-/_ only.'
        ),
        validators=[
            RegexValidator(
                r'^[\w.@+-]+$',
                _('Enter a valid username. '
                    'This value may contain only letters, numbers '
                    'and @/./+/-/_ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("A user with that username already exists."),
        })
    GENDER_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    birth_date = models.DateField(null=True, blank=True)
    picture = models.ImageField(
        null=True,
        blank=True,
        upload_to='account_pictures/',
    )
    email = models.EmailField(unique=True, null=False, blank=False)
    contact_no = models.IntegerField(unique=True, blank=True, null=True)
    deposit_product=models.ForeignKey(
                                    DepositProduct,
                                    null=True
                                    )
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def account_no(self):
        if hasattr(self, 'account'):
            return self.account.account_no
        return None

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return None

    @property
    def full_address(self):
        if hasattr(self, 'address'):
            return '{}, {}-{}, {}'.format(
                self.address.street_address,
                self.address.city,
                self.address.postal_code,
                self.address.country,
            )
        return None


class AccountDetails(models.Model):

    user = models.OneToOneField(
        User,
        related_name='account',
        on_delete=models.CASCADE,
    )
    account_no = models.PositiveIntegerField(
        unique=True,
        validators=[
            MinValueValidator(10000000),
            MaxValueValidator(99999999)
        ]
    )

    balance = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )

    def __str__(self):
        return str(self.account_no)


class UserAddress(models.Model):
    user = models.OneToOneField(
        User,
        related_name='address',
        on_delete=models.CASCADE,
    )
    street_address = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    postal_code = models.PositiveSmallIntegerField()
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.email

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.db.models import Sum
from django.shortcuts import render

from transactions.models import Diposit, Withdrawal, Interest,DepositProduct


def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/home.html", {})
    else:
        user = request.user
        deposit = Diposit.objects.filter(user=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']
        deposit_product=DepositProduct.objects.filter(user=user)
        deposit_product_sum = deposit_product.aggregate(Sum('number_of_proc'))['deposit_procent']
        context = {
                    "user": user,
                    "deposit": deposit,
                    "deposit_sum": deposit_sum,
                    "withdrawal": withdrawal,
                    "withdrawal_sum": withdrawal_sum,
                    "interest": interest,
                    "interest_sum": interest_sum,
                    "deposit_product": deposit_product_sum
                  }

        return render(request, "core/transactions.html", context)


def about(request):
    return render(request, "core/about.html", {})

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} About | {{ block.super }}{% endblock title %}

{% block content %}

<h1>About US</h1>
<hr>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Why do we use it?</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
</p>


<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>

{% endblock content %}

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} Banking System {% endblock title %}</title>

    <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
{% include "core/navbar.html" %}

<div class="container" style="padding-top: 60px;">
{% block content %}

{% endblock content %}
</div>
{% include "core/footer.html" %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/footer.html
<hr>
<footer class="footer navbar-fixed">
    <!--Footer Links-->
    <div class="container-fluid">
        <div class="row">
            <!--First column-->
            <div class="col-md-6">
                <h4 class="title"><b>Footer Content</b></h4>
                <p>Here you can use rows and columns here to organize your footer content.</p>
            </div>
            <!--/.First column-->
            <!--Second column-->
            <div class="col-md-6">
                <h5 class="title"><b>Links</b></h5>

                <a href="{% url 'home' %}">Home </a>|
                <a href="{% url 'about' %}">About Us</a> |&nbsp;


            </div>
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->
    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
            © 2017 Copyright: <a href="http://127.0.0.1:8000/"> banking-system.com</a>
        </div>
    </div>
    <!--/.Copyright-->
</footer>
<br>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %} {{ block.super }}{% endblock title %}

{% block content %}
<div class="container" style="padding-top: 50px;">
<div class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Banking System</h1>
        <hr>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
          <a class="btn btn-primary btn-md" href="{% url 'accounts:login' %}" role="button">Load Account Details</a>
          <a class="btn btn-success btn-md" href="{% url 'accounts:register' %}" role="button">Create a Bank Account</a>
        </p>
      </div>
</div>
</div>

{% endblock content %}

core/templates/core/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">Banking System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'transactions:deposit' %}">Deposit</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About Us</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger btn-sm" type="button">Logout</a>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-success btn-sm" type="button">Load Account Details</a> |
            <a href="{% url 'accounts:register' %}" class="btn btn-primary btn-sm" type="button">Create an Account</a>
        {% endif %}
    </form>
  </div>
</nav>

core/templates/core/transactions.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}

    <div class="page-header">
      <h1 class="text-center"><b>Banking System</b><br><small>ABC Bank Ltd.</small></h1>
    </div>
    
<div class="row">

  <div class="col-xs-12 col-md-8 text-left">
    <h4><b>Account Name: </b>{{ user.full_name }}</h4>
    <h4><b>Date of Birth: </b>{{ user.account.birth_date }}</h4>
    <h4><b>Gender: </b>{{ user.account.get_gender_display }}</h4>
    <h4><b>Contact No: </b>{{ user.contact_no }}</h4>
    <h4><b>Email Address: </b>{{ user.email }}</h4>
    <h4><b>Address: </b>{{ user.full_address }}</h4>
  </div>
  <div class="col-xs-6 col-md-4 text-left">
    <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
    <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>
    <div class="well">
    <h4 class="card"><b>Account Balance: </b>{{ user.balance }} $</h4>
    <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
    <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
    </div>
  </div>

</div>

<hr>

  <div class="page-header">
  <h2 class="text-center"><b>Transaction Details</b></h2>
</div>

<h3>Deposit Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in deposit %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Deposit</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ deposit_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>


<h3>Withdrawal Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in withdrawal %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Withdrawal</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ withdrawal_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>


<h3>Interest Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in interest %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Interest</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ interest_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>

    <h3>Deposit Product</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>number_of_proc (%)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{ obj.timestamp }}</td>
      <td>Deposit product</td>
      <td>{{deposit_product}}</td>
    </tr>
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ deposit_sum }}</td>
    </tr>

  </tbody>
</table>
<hr>
{% endblock content %}